name: Zig CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.17.0
      - run: zig test bump.zig
      - run: zig fmt --check bump.zig
